all: p1 p2 p3 p4 p5 p6

p1: p1/p1
p1/p1: p1/p1.o

p2: p2/p2
p2/p2: p2/p2.o

p3: p3/p3
p3/p3: p3/p3.o

p4: p4/p4
p4/p4: p4/p4.o

p5: p5/p5
p5/p5: p5/p5.o

p6: p6/p6
p6/p6: p6/p6.o

clean:
	rm p1/*.o p2/*.o p3/*.o p4/*.o p5/*.o p6/*.o